// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnZPyq_nAYu3mdd9JNreAOdKig4cHgIE',
    appId: '1:499763437222:web:ec03e1a1a7664919891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    authDomain: 'flutter-auth-a8d16.firebaseapp.com',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    measurementId: 'G-9X2ZV4GBZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZFxzUrBpqjMO5VUOM1-kr3px3I9_PYAI',
    appId: '1:499763437222:android:ba806e519ae9d1e6891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYp2lmgWJcJbB81kxa3nKGAGV9J6KhXpI',
    appId: '1:499763437222:ios:789227d9090686e7891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYp2lmgWJcJbB81kxa3nKGAGV9J6KhXpI',
    appId: '1:499763437222:ios:789227d9090686e7891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJnZPyq_nAYu3mdd9JNreAOdKig4cHgIE',
    appId: '1:499763437222:web:89e9a455912ac03a891e67',
    messagingSenderId: '499763437222',
    projectId: 'flutter-auth-a8d16',
    authDomain: 'flutter-auth-a8d16.firebaseapp.com',
    storageBucket: 'flutter-auth-a8d16.firebasestorage.app',
    measurementId: 'G-DL44DZLG9F',
  );
}
